import { useEffect, useState } from "react";
import { API } from "aws-amplify";
import Head from "next/head";
import { listBlogs } from "../src/graphql/queries";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [blogs, setBlogs] = useState([]);
  useEffect(() => {
    async function getBlogs() {
      const result = await API.graphql({ query: listBlogs });
      console.log("blogs", result);
      setBlogs(result.data.listBlogs.items);
    }
    getBlogs();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to AmplifyNextTester</h1>
        <h4>Public route</h4>
        {blogs.map((blog) => {
          return <p>{blog.name}</p>;
        })}
      </main>
    </div>
  );
}
