import Head from "next/head";
import styles from "../styles/Home.module.css";
import { View } from "@aws-amplify/ui-react";
import { RequireAuth } from "../components/RequireAuth";
function Protected() {
  return (
    <RequireAuth>
      <View className={styles.container}>
        <Head>
          <title>Protected</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Protected</h1>
        </main>
      </View>
    </RequireAuth>
  );
}

export default Protected;
