import react, { useEffect, useState } from "react";
import Head from "next/head";
import { withAuthenticator } from "@aws-amplify/ui-react";
import { Amplify, API, Auth, graphqlOperation } from "aws-amplify";
import { GRAPHQL_AUTH_MODE } from "@aws-amplify/api";
import styles from "../styles/Home.module.css";
import "@aws-amplify/ui-react/styles.css";
import MessageForm from "../components/MessageForm";
import MessageApp from "../components/MessageApp";

const onCreateMessageSubscription = /* GraphQL */ `
  subscription onCreateMessage($owner: String!) {
    onCreateMessage(owner: $owner) {
      id
      senderEmail
      firstname
      lastname
      createdAt
      type
      recipients
      subject
      body
      isRead
      owner
    }
  }
`;

const getInboxMessages = /* GraphQL */ `
  query getReceivedMessages($recipient: ID!) {
    messagesByRecipient(recipientId: $recipient, filter: { type: { eq: received } }, sortDirection: DESC) {
      items {
        id
        senderEmail
        firstname
        lastname
        createdAt
        type
        recipients
        subject
        body
        isRead
      }
    }
  }
`;

function Protected({ signOut, user }) {
  const [inbox, setInbox] = useState([]);

  useEffect(() => {
    const getUnreadMessages = async () => {
      try {
        const { data, errors } = await API.graphql({
          query: getInboxMessages,
          variables: {
            recipient: user.attributes.sub,
          },
          authMode: GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS,
        });
        if (!errors) {
          setInbox(data["messagesByRecipient"].items);
        } else {
          throw new Error("Set Messages Error");
        }
      } catch (err) {
        console.log(err);
      }
    };
    getUnreadMessages();
  }, [user]);

  useEffect(() => {
    const subscription = API.graphql(
      graphqlOperation(onCreateMessageSubscription, { owner: user.attributes.sub })
    ).subscribe({
      next: (messageData) => {
        // When a new message is created, it will trigger this callback
        const message = messageData.value.data.onCreateMessage;
        console.log("subscription Message", message);
        if (message.type === "received") {
          setInbox([message, ...inbox]);
        }
      },
      error: (error) => {
        console.error("Subscription Error:", error);
      },
    });

    return () => {
      // Unsubscribe when the component unmounts
      subscription.unsubscribe();
    };
  }, [inbox, user.attributes.sub]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Messaging</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Messaging</h1>

        <MessageApp messages={inbox} />
      </main>
    </div>
  );
}

export default withAuthenticator(Protected, { loginMechanisms: ["email"] });
