import Head from "next/head";
import { withAuthenticator } from "@aws-amplify/ui-react";
import styles from "../styles/Home.module.css";
import "@aws-amplify/ui-react/styles.css";

function Protected({ signOut, user }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to AmplifyNextTester</h1>
        <h4>Protected route non SSR</h4>
        <button onClick={signOut}>Sign Out</button>
      </main>
    </div>
  );
}

export default withAuthenticator(Protected, { loginMechanisms: ["email"] });
