import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Amplify, API } from "aws-amplify";
import { listBlogs } from "../../src/graphql/queries";
import styles from "../../styles/Home.module.css";

export default function Blogs() {
  const [blogs, setBlogs] = useState([]);

  useEffect(() => {
    async function getBlogs() {
      const result = await API.graphql({ query: listBlogs });
      console.log("blogs", result);
      setBlogs(result.data.listBlogs.items);
    }
    getBlogs();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Blogs</h1>
        {blogs &&
          blogs.map((blog) => {
            return (
              <Link key={blog.id} href={`/blogs/${blog.id}`}>
                <a>
                  <p>{blog.name}</p>
                </a>
              </Link>
            );
          })}
      </main>
    </div>
  );
}
